spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: product-detail
          uri: lb://product-detail
          predicates:
             - Path=/addProduct/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      enable: true
      sampler:
        probability: 1 #100% (default = 10%)
