spring:
  zipkin:
    base-url: http://172.17.0.2:9411/
    sleuth:
      enable: true
      sampler:
        probability: 1 #100% (default = 10%)

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
