
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      enable: true
      sampler:
        probability: 1 #100% (default = 10%)
